/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacejava;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author htaeaquino
 */
public class TelaInserirJogos extends javax.swing.JFrame {

    /**
     * Creates new form TelaInserirJogos
     */
    public TelaInserirJogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panOpcoes = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaInserir = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJogo = new javax.swing.JTextField();
        txtPlacar = new javax.swing.JTextField();
        btnSalvarJogos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inserir Jogos");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(734, 517));

        panOpcoes.setName(""); // NOI18N
        panOpcoes.setPreferredSize(new java.awt.Dimension(493, 304));
        panOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        panOpcoes.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabelaInserir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Placar"
            }
        ));
        jScrollPane1.setViewportView(jTabelaInserir);

        panOpcoes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 560, 210));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 24)); // NOI18N
        jLabel1.setText("Insira seus jogos ");
        panOpcoes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        jLabel2.setText("Jogo:");
        panOpcoes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        jLabel3.setText("Placar:");
        panOpcoes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        txtJogo.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        panOpcoes.add(txtJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 90, -1));

        txtPlacar.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        panOpcoes.add(txtPlacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 90, -1));

        btnSalvarJogos.setText("Salvar jogos");
        btnSalvarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarJogosActionPerformed(evt);
            }
        });
        panOpcoes.add(btnSalvarJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new TelaOpcoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarJogosActionPerformed
        // Recuperar os dados preenchindos pelo usuario
        int jogo = Integer.parseInt(txtJogo.getText());
        int placar = Integer.parseInt(txtPlacar.getText());
        // Condicao para dados ja cadastrados
        if (jogo <=4) {
               JOptionPane.showMessageDialog(null, "Este jogo já está cadastrado!");
               txtJogo.setText("");
               txtPlacar.setText("");
           
           } else {
        
         //Conversao da jTabelaInserir
        DefaultTableModel tabelaJogos = 
                (DefaultTableModel)jTabelaInserir.getModel();
        Object[] novoJogo = new Object[] {
            jogo, //posicao 1 do array
            placar // posicao 2 do array
        }; 
            //Adiciona uma linha na tabela para inserir novos jogos
           tabelaJogos.addRow(novoJogo);
           //LimparCampos
           txtJogo.setText("");
           txtPlacar.setText("");
           
           
          
           
        }
        
        
    }//GEN-LAST:event_btnSalvarJogosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInserirJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInserirJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInserirJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInserirJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInserirJogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarJogos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaInserir;
    private javax.swing.JPanel panOpcoes;
    private javax.swing.JTextField txtJogo;
    private javax.swing.JTextField txtPlacar;
    // End of variables declaration//GEN-END:variables
}
